version: 2
orbs:
  do-exclusively: miyajan/do-exclusively@0.1.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build
          command: npm run build
      
      - deploy:
          name: Push to Dokku
          steps:
            - do-exclusively/do-exclusively:
              token: $CIRCLE_TOKEN
              command: |
                echo $CIRCLE_BRANCH
                echo $SHOULD_DEPLOY
                if [[ "$CIRCLE_BRANCH" != "master" && "$SHOULD_DEPLOY" != "true" ]]; then
                  echo "not deploying"
                  exit 0
                else
                  ssh-keyscan -H mgnt.work >> ~/.ssh/known_hosts
                  git config --global user.email "app@dillonpetito.com"
                  git config --global user.name "Dokku"
                  git commit --allow-empty -m "Empty Commit to setup deployments"
                  git remote add staging dokku@mgnt.work:mosaic
                  git push -f staging master
                fi

  # deploy:
  #   machine:
  #       enabled: true
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run:
  #         name: Push to Dokku
  #         command: |
  #           ssh-keyscan -H mgnt.work >> ~/.ssh/known_hosts
  #           git remote add staging dokku@mgnt.work:mosaic
  #           git push staging master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #         - build
      #     filters:
      #       branches:
      #         only: master
