version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build
          command: npm run build
      
      - deploy:
          name: Push to Dokku
          command: |
            if [[ "$CIRCLE_BRANCH" != "master" && "$CIRCLE_TAG" != "deploy" ]]; then
              exit 0
            else
              ssh-keyscan -H mgnt.work >> ~/.ssh/known_hosts
              git remote add staging dokku@mgnt.work:mosaic
              git push staging master
            fi

  # deploy:
  #   machine:
  #       enabled: true
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run:
  #         name: Push to Dokku
  #         command: |
  #           ssh-keyscan -H mgnt.work >> ~/.ssh/known_hosts
  #           git remote add staging dokku@mgnt.work:mosaic
  #           git push staging master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #         - build
      #     filters:
      #       branches:
      #         only: master
