version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build
          command: npm run build

  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add Dokku to known_hosts
          command: ssh-keyscan -H mgnt.work >> ~/.ssh/known_hosts
      - run: git remote add staging dokku@mgnt.work:mosaic
      - run: git push staging master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build
          filters:
            branches:
              only: master
